### ISSUE TITLE
In container?

### ISSUE THREAD

**Issue by JanMisker** [hackersanddesigners/the-hmm-livestream#5]
Hey,
Looks nice, but there seems to be quite some configuration.
Did you consider to containerise it using Docker?

**Comment by sonn-gamm** [comment]
Hi @JanMisker!

I don't think Docker would bring any benefit to this. The advantage of automatic builds (`npm run install && npm run deploy`) are counterbalanced by having to set some values to `settings.json` and `.env` anyway. The `nginx` settings are very minimal.

Maybe the README is a bit too detailed and gives the impression of a lot of work, whereas it's fairly quick to setup a new instance.
